pipeline {
    agent any

    environment{
        DOCKER_IMAGE_NAME = "ashishalva/hello-python"
    }


    stages {
        
        stage('Checkout') {
            steps {
                // This downloads your repo into the workspace
                git branch: 'main', url: 'https://github.com/Ashish-Alva/30-Day-Devops.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('8_jenkins_CI') {
                    // This command uses the Dockerfile to build the image
                    script{
                        app = docker.build("${DOCKER_IMAGE_NAME}:latest")
                    }
                    
                }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Login using your Docker Hub credentials stored in Jenkins
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.image("${DOCKER_IMAGE_NAME}:latest").push()
                    }
                }
            }
        }
        
        stage('Stage 1 : Greetings') {
            steps {
                echo 'Hello World'
            }
        }
        
        stage('Stage 2 : Install Git and python dependencies') {
            steps {
                sh '''
                    sudo dnf install git -y
                    sudo dnf install -y python3    
                '''            
            
            }
            
        }
        
            stage('Stage 3 : Run Python file') {
            steps {
                 
                    dir('8_jenkins_CI'){
                        sh  'python3 hello.py'
                    }
                  
                    
            
            }
            
        }
        
        
        }
    }
}
